# -*- coding: utf-8 -*-
"""bwikipedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CjjwP4YuYRuyAe5mwGE7SH5-xDSt1GLz
"""



import wikipedia
print("write Done to stop searching")
while(1):
  print(">>>>")
  a = input()
  if (a == "Done"):
    break
  res = wikipedia.summary(a)
  print(res)
